### ISSUE TITLE
Script without heating mitsubishi

### ISSUE THREAD

**Issue by smartboart** [timjong93/growatt_mqtt#1]
hello, i have tried to remove the heating states  / mitsubihi Registeres out of the code, becauswe i do not nee it...I was not able to do so..Can you helP?

The Sketch works perfect with my growatt....Thank you for this.... I have added a input register 
      publishFloat("energy/growatt/Temperatur", glueFloat(0, node.getResponseBuffer(32)));
      
      publishFloat("energy/growatt/Faultcode", glueFloat(0, node.getResponseBuffer(40)));

Temperatur is delivering always 0... Faultcode is working....do you have an idea for that?

Thanks

**Comment by timjong93** [comment]
Hi,

Did you see the feature/integration branch? This is more up to date than the current master.
As for your issue it's difficult to help you based on the information you provided. If you would fork this repo and push your changes i could have a look.

**Comment by smartboart** [comment]
Yes i have watched it....But i just need to get the information from my growatt inverter...I just need the master branch getting to work without the mitsubishi function... Only growatt...

And i have added the input register for Inverter Temperature, but this is the only input register which is not polling the correct values...It just polls a 0...

i hav just added this line ..

publishFloat("energy/growatt/Temperatur", glueFloat(0, node.getResponseBuffer(32)));

**Comment by timjong93** [comment]
So i never saw your reply, i'm sorry.
Propably this is to late, but if you are still interested.

Which registers are available depends on the model of your inverter, are you sure this register is actually set by the inverter?
I would suggest to use the current master branch and remove the stuff you dont need as it also contains a number of stability fixes.

**Comment by smartboart** [comment]
Thanks for information... Yes this register is activ and was working in another solution... But your way is better for me....

Can you add this register to your code?

**Comment by smartboart** [comment]
Hi again, i having this error while compiling your scetch... any idea..
no matching function for call to 'SoftwareSerial::SoftwareSerial(int, int, bool, int)'

**Comment by smartboart** [comment]
found a solution, needed to downgrade ESP8266 to Version 2.5.2. in arduino.Then it worked...

**Comment by smartboart** [comment]
I was able to change the project so that i only have the growatt inverter activ..all other devices and not needed functions i have removed from the code..
issue can be closed..
